root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.eslint.json
plugins:
  - react
  - "@typescript-eslint"
  - filenames
settings:
  react:
    version: detect
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - prettier
rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-unused-vars":
    - "error"
    - varsIgnorePattern: "^_"
  react/react-in-jsx-scope: "off"
  filenames/match-exported: error
overrides:
  - files:
      - next.config.js
    env:
      node: true
  - files:
      - samples/**
    rules:
      no-irregular-whitespace: "off"
  - files: pages/**
    rules:
      filenames/match-exported: "off"
  - files: [types/**, server/types/**]
    rules:
      filenames/match-exported: [error, camel]
