name: build
on: pull_request
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
      - uses: actions/checkout@v2
      - id: yarn_cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn_cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-
      - run: yarn
  format:
    needs: install
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
      - run: yarn format
      - id: git_status
        run: echo "::set-output name=mod::$(git status --porcelain)"
      - if: steps.git_status.outputs.mod != ''
        run: |
          git -c "user.name=bot" -c "user.email=bot@example" commit -a -m "bot: format"
          git push origin HEAD
  lint:
    needs: [install, format]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
      - run: yarn lint
  build:
    needs: [install, format]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}
      - run: yarn build
