name: deploy
on:
  push:
    # FIXME: NEXT_PUBLIC_LMS_URL など実際の環境に合わせたパラメーターを何かしらの手段で与えないと動かない
    branches: [dummy]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: install -m 700 -d ~/.ssh
      - run: install -m 600 <(echo '${{ secrets.DEPLOY_KEY }}') ~/.ssh/deploy_key
      - run: >
          ssh
          -i ~/.ssh/deploy_key
          -o 'StrictHostKeyChecking no'
          ${{ secrets.DEPLOY_USER }}@lti.cccties.org
          'bash -lc "cd /var/www/html/lti && git pull --rebase && yarn && yarn build"'
